//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public int floor { get; set; }
        public int places { get; set; }
        public string kitchen { get; set; }
        public string bathroom { get; set; }
        public bool discount { get; set; }
        public decimal price { get; set; }
        public int size { get; set; }
        public string view { get; set; }
    
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
