//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string country { get; set; }
        public System.DateTime birth_date { get; set; }
        public bool admin { get; set; }
    
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
